### ISSUE TITLE
The name of the given podspec `RNCPushNotificationIOS` doesn't match the expected one `RNPushNotificationIOS`

### ISSUE THREAD

**Issue by apamphilon** [react-native-community/react-native-push-notification-ios#11]
Should the `RNPushNotificationIOS.podspec` be renamed to `RNCPushNotificationIOS.podspec`?

**Comment by Embraser01** [comment]
For those searching a solution, you can change your `Podfile` by:

```
# Can be reverted when #9 is merged
pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios/RNPushNotificationIOS.podspec'
```

**Comment by Return-1** [comment]
is this receiving attention?

**Comment by thymikee** [comment]
Published in v1.0.2

**Comment by Air-Rands** [comment]
@thymikee im still having this issue on v1.0.2 and "react-native": "0.58.5"

**Comment by thymikee** [comment]
@Air-Rands the podspec is now in sync with the file name. Please file a new issue with a repro and clear description of what's wrong
