### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by janczizikow** [react-native-community/react-native-push-notification-ios#29]
# Feature Request

Add TypeScript declarations to the repo, could be extracted from `@types/react-native`.

### Code sample

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L7410

Would a PR be welcome or is it preferable to keep typings at DefinitelyTyped?

**Comment by idanlo** [comment]
any updates on this? Very hard to use this on a TypeScript project

**Comment by Naturalclar** [comment]
1.0.5 has been released with `index.d.ts` for typescript support :tada:
