### ISSUE TITLE
Duplicate declaration of method 'application:didRegisterForRemoteNotificationsWithDeviceToken:'

### ISSUE THREAD

**Issue by russelRajitha** [react-native-community/react-native-push-notification-ios#31]
in my react native project i installed `RNCPushNotificationIOS`. and now i am receiving error when added codes given into `AppDelegate.m`. i copied it from example project and `Readme.md`. can some one help me? i am not good with ios. 
```
RN version : 0.60
/Users/admin/Experiment/ios/experiment/AppDelegate.m:58:1: Duplicate declaration of method 'application:didRegisterForRemoteNotificationsWithDeviceToken:'
```
line 58
```
// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken

```

**Comment by calvinaquino** [comment]
I had the same thing, it so happens that the old `RCTPushNotification.xcodeproj` still exists (and it declares the same methods, probably made this way for ease of migration).
All you need to do is to delete it.
It should be located in the `Libraries` folder on Xcode.

**Comment by russelRajitha** [comment]
@calvinaquino  thanks. it worked

**Comment by Naturalclar** [comment]
Closing this issue for house keeping.
Thanks @calvinaquino for the solution :)
