### ISSUE TITLE
Version 1.0.4 causes build error with TS 3.6.4

### ISSUE THREAD

**Issue by iartemiev** [react-native-community/react-native-push-notification-ios#59]
# Bug

Experiencing TypeScript build issue since updating to version 1.0.4 with TypeScript 3.6.4

The following import:
```typescript
import PushNotificationIOS from '@react-native-community/push-notification-ios';
```

causes `tsc` to error out with:

```
../../node_modules/@react-native-community/push-notification-ios/index.d.ts(264,1): error TS2309: An export assignment cannot be used in a module with other exported elements.
```

Pinning version to 1.0.3 resolves the issue.

**Comment by Naturalclar** [comment]
@iartemiev 
Thanks for opening an issue!
Released v1.0.5 to fix this error.
