### ISSUE TITLE
LocalNotification not working [IOS]

### ISSUE THREAD

**Issue by meetsiraja** [react-native-community/react-native-push-notification-ios#71]
# Question

I followed all the documentation properly. Still, LocalNotification is not working. 

This is my environment config:
- `react-native` : `0.61.4`
- `@react-native-community/push-notification-ios --save` : `1.0.5`

I did the following things,

1. `npm i @react-native-community/push-notification-ios --save`
2. `cd ios && pod install`
3. Updated `AppDelegate.m` as per described [here](https://github.com/react-native-community/react-native-push-notification-ios#update-appdelegatem)
4. Then calling function in my js like this,
```js
import PushNotificationIOS from "@react-native-community/push-notification-ios";
.
.
.
componentDidMount(){
  PushNotificationIOS.addEventListener('localNotification', this._onNotification);
  
  PushNotificationIOS.requestPermissions();
  PushNotificationIOS.presentLocalNotification({
    alertBody: 'Test Notification'
  });
}

_onNotification(notification) {
  console.log(notification._alert);
}
.
.
.
```
- By the way, It requests for permissions when the first-time app opens & also I'm getting `console.log` of notification but not getting any local notification.

**Comment by kuls14** [comment]
If you are checking for local notification when the app is in the foreground, you won't get any notification that is the default behavior of iOS. for more info read this documentation.
[https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html)

**Comment by meetsiraja** [comment]
@kuls14 Then what is the purpose of this function: `PushNotificationIOS.presentLocalNotification`

**Comment by kuls14** [comment]
I'm not 100% sure but this is used when we get a push notification and then we need to trigger that push notification as localNotification. 
If you want to set a local notification to fire after a certain time interval or at a certain time in future you can use `scheduleLocalNotification`.

**Comment by meetsiraja** [comment]
Okay, Thanks @kuls14

**Comment by kuls14** [comment]
you can also check #63

**Comment by mzupek** [comment]
> I'm not 100% sure but this is used when we get a push notification and then we need to trigger that push notification as localNotification.
> If you want to set a local notification to fire after a certain time interval or at a certain time in future you can use `scheduleLocalNotification`.

This is not correct - I have used localNotifcaiton in the foreground many times.
