### ISSUE TITLE
notification - Event

### ISSUE THREAD

**Issue by Psiiirus** [react-native-community/react-native-push-notification-ios#72]
Hi,
the RN documentation says that the "notification" will be invoked if a remote notification is received unfortunately it seems that this isn't true.
My handler only gets called if the user clicks on a specific notification, is this the right behavior or a bug?

Thanks

**Comment by dominiczaq** [comment]
notification event will be called only when the app is in the foreground

**Comment by Psiiirus** [comment]
@dominiczaq  thanks for the fast reply....so if i want to track the conversion of my notification.
e.g. "Notification send -> Notification received -> Notification clicked"
This wont be possible, right?

**Comment by dominiczaq** [comment]
@Psiiirus try to add console.logs to see how notification event works.

Afaik the default behaviour is at follows:
- if the app is in the foreground you will receive `notification` event, but the notification itself won't be displayed - it's the default behaviour. You can handle displaying notifications in the foreground by following steps from this issue: https://github.com/react-native-community/react-native-push-notification-ios/issues/63#issuecomment-583618575 Obviously you will be able to track your `Notification received` event.
- if the app is in the background you won't receive `notification` event after push notification is delivered. Instead, the handler will run when you click on the notification. So in that case you'll be able to track your `Notification clicked` event.

You can use AppState http://reactnative.dev/docs/appstate to detect whether your app is in foreground or background state.

imho to track your events:
1. Notification send - depends on the type of the notification, if you send local notification track it there, if you send remote notification i.e via APNS you must track it on the server
2. Notification received - you can track it in native code. To make this package work you currently must add code to AppDelegate.m - check which one receives incoming push notification event and track it there
3. Notification clicked - as I said before, depends if you display notification in the foreground or only in the background.

**Comment by Psiiirus** [comment]
@dominiczaq  thanks for this really detailed answer! 
This sound like a nice extra feature for this lib...maybe i can find some time in the next weeks do do a PR
